### ISSUE TITLE
大佬您好，我想问下，关注公会的那个功能是怎么使用的呢

### ISSUE THREAD

**Issue by Noire821** [Sakurayia/HoshinoBotClanRank#1]
群内输入了关注公会+公会名，但是没有反应，单独打关注公会也是这样，是需要单独启用吗

**Comment by Sakurayia** [comment]
这个功能是默认关闭的，怕给有的群带来打扰，你需要先启用 clanrank-reminder

**Comment by Noire821** [comment]
在bot的那个文件里启用这个功能是吗，谢谢大佬

**Comment by Sakurayia** [comment]
不用，直接管理员在要启用的群里发送“启用 clanrank-reminder”就行

**Comment by Noire821** [comment]
好的，谢谢大佬
